### ISSUE TITLE
"Define" integration with Capabilities

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#1003]
I'm not quite clear what "Define" means here and the link leads to somewhere that doesn't clarify that

![Screenshot 2023-12-14 at 11 09 23 AM](https://github.com/publishpress/PublishPress-Permissions/assets/3868028/4a39e94c-896c-42bd-8b72-8964d28c8995)

**Comment by agapetry** [comment]
Resolved within Capabilities Pro
