### ISSUE TITLE
Undefined Array after latest update

### ISSUE THREAD

**Issue by mbiolsi** [publishpress/PublishPress-Permissions#1063]
## Current Behavior

After the latest update, there is an error at the top of the WP admin that says, "Warning: Undefined array key "cols" in /wp-content/plugins/press-permit-core/classes/PublishPress/Permissions/DB/Groups.php on line 424"

There was no error prior to updating plugin to 4.0.19

## Possible Solution

Could not find a fix. Tried going into groups and editing a group and saving it. Still have the error. 

## Steps to Reproduce (for bugs)

1. Install latest version. 

## Your Environment

* Version used: 4.0.19
* Browser Name and version: Chrome Version 122.0.6261.71 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 11, Microsoft Surface Laptop
* Link to your project: https://coughlin.co

**Comment by agapetry** [comment]
@mbiolsi This fixed by the attached PR and the Permissions 4.0.20 release. Thanks for reporting.
