### ISSUE TITLE
Warning: Undefined array key “cols” 

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Permissions#1064]
Permissions version 4.0.19 has this warning

Warning: Undefined array key “cols” in /customers/7/5/e/****/httpd.www/cultuur/wp-content/plugins/press-permit-core/classes/PublishPress/Permissions/DB/Groups.php on line 424 Warning: Cannot modify header information – headers already sent by (output started at /customers/7/5/e/lucasgent.be/httpd.www/cultuur/wp-content/plugins/press-permit-core/classes/PublishPress/Permissions/DB/Groups.php:424) in /customers/7/5/e/****/httpd.www/cultuur/wp-admin/includes/misc.php on line 1431

**Comment by agapetry** [comment]
Closing as duplicate: https://github.com/publishpress/PublishPress-Permissions/issues/1063
