### ISSUE TITLE
Limit None Configuration Does not Include New Post

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Permissions#1106]
The solution that we provide here: https://publishpress.com/knowledge-base/block-users-from-reading-all-posts/

If there is any new post, it will not be included. Can we make sure that new post also affected?

Original report: https://wordpress.org/support/topic/revoking-reading-capabilities-for-custom-post-types/

**Comment by agapetry** [comment]
@rizaardiyanto1412 This is a misunderstanding, explained here: https://wordpress.org/support/topic/revoking-reading-capabilities-for-custom-post-types/
