### ISSUE TITLE
Can we improve this error message?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#1148]
![Screenshot 2024-08-29 at 5 01 47 PM](https://github.com/user-attachments/assets/f0f34079-d111-4f8a-b8c0-d48b220af27b)

https://secure.helpscout.net/mailbox/b2040204d7e2f5f6/2557458/

**Comment by agapetry** [comment]
The last PR changes that caption to "Visibility Circle restrictions do not apply to this role, since it has the pp_exempt_read_circle capability.
