### ISSUE TITLE
Permission PRO 4.0.29 translation updates

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Permissions#1155]
Hi @andergmartins , @stevejburge 

Here's copy of the Permission PRO 4.0.29 translation updates for ES-FR-IT. Please add to new languages folder

**Comment by agapetry** [comment]
@wocmultimedia Can you please post a new link to these translation? Rather than a languages folder, you linked a copy to the full plugin package, which did not seem to have changes to languages. We don't want the full plugin package posted here.

**Comment by wocmultimedia** [comment]
Hi,
I'm sorry for the inconvenient
[PermissionPRO_4.0.29_translationUpdates.zip](https://github.com/user-attachments/files/17105107/PermissionPRO_4.0.29_translationUpdates.zip)

**Comment by agapetry** [comment]
Replaced by #1175
