### ISSUE TITLE
Equalize the "Groups" headings

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#1192]
Can we have consistent widths and alignment on the table header of these screens?
/wp-admin/admin.php?page=presspermit-groups
![Screenshot 2024-10-14 at 1 56 09 PM](https://github.com/user-attachments/assets/678dbd69-655a-44a2-8f21-0f27351716fb)

**Comment by agapetry** [comment]
@stevejburge I think we should at least support a "narrow column" class. The Users count will never be as wide as the others, so why force line breaks in other columns by putting extra space there?  In actual use cases, the Roles and Permissions column can get a little crowded, so making them narrower will not be helpful.
