### ISSUE TITLE
Improve design of items added via the "Posts" screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#1218]
This is the screen you see when editing a "Group".

After adding a new item via the "Posts" screen, the data is very unformatted

Can we remove the yellow text and add clearer formatting?

![Screenshot 2024-11-11 at 2 21 33 PM](https://github.com/user-attachments/assets/2e24e259-8603-497e-94e0-623df8a18e0a)

**Comment by stevejburge** [comment]
Sorry, still seeing this

**Comment by richaferry** [comment]
Hi @stevejburge ,
For this issue, what kind happen is? Because in my side already formatted. And yellow text intendeed show related this issue https://github.com/publishpress/PublishPress-Permissions/issues/1257 to changes wording.

**Comment by richaferry** [comment]
![Screenshot_2024-12-18_02-09-01](https://github.com/user-attachments/assets/1f3351aa-7e0d-4b6f-9f44-1c4c324f08c0)
![Screenshot_2024-12-18_02-08-48](https://github.com/user-attachments/assets/5e349a1b-b730-4ae7-af5b-24c9fec9f155)
Here is my side. This is settings group screen right?

**Comment by stevejburge** [comment]
@richaferry Yes, I don't think it's successfully committed yet.
