### ISSUE TITLE
Permissions metabox value is not being saved

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Permissions#1234]
![image](https://github.com/user-attachments/assets/d43bab6c-2207-45df-9faa-29d5314902d9)

**Comment by stevejburge** [comment]
The same is true with this field
![Screenshot 2024-11-14 at 11 02 36 AM](https://github.com/user-attachments/assets/cf293d5a-236b-4286-9e3c-de886c936fc3)
