### ISSUE TITLE
Remove "Editor Options" icon

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#1253]
![Screenshot 2024-11-15 at 1 21 18 PM](https://github.com/user-attachments/assets/f6b006f5-d4d6-40d8-99c8-a7806de69cb7)

**Comment by agapetry** [comment]
@richaferry @stevejburge To avoid breaking existing functionality, you may need to implement a simple js script to hide the hints icon if there are no hints on the tab. In some cases, additional settings may be displayed when certain modules (or other PublishPress plugins) are active.
