### ISSUE TITLE
Remove "Statuses" notice in Permissions Pro

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#1254]
![Screenshot 2024-11-15 at 1 24 22 PM](https://github.com/user-attachments/assets/9d2c11f3-5601-44c4-bc03-978fef5a5196)

**Comment by richaferry** [comment]
Hi @stevejburge ,
If we remove this notification i think we need moved into settings. because this notification being traffic into installed Statuses. I just worried if our new user confuse to use statuses. which is separately plugin.

**Comment by stevejburge** [comment]
@richaferry That's OK. Almost anyone who needed Statuses has already moved
