### ISSUE TITLE
Improve the design of the "Add Supplemental Roles" tab

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#1257]
Related: https://github.com/publishpress/PublishPress-Permissions/issues/1218

Can we improve the design of this to match the issue above?

Let's change the text also: "Review the selection below, and then click "Save Roles"."

![Screenshot 2024-11-15 at 1 29 16 PM](https://github.com/user-attachments/assets/89a6d64b-55ac-4e0f-93c2-0a4195d5827e)

**Comment by stevejburge** [comment]
Sorry, I'm not seeing that change yet
![Screenshot 2024-12-17 at 1 09 22 PM](https://github.com/user-attachments/assets/a61aaadf-e7fb-49cf-9aae-e9d519d57f19)

**Comment by richaferry** [comment]
Is it pro or free version @stevejburge ?

**Comment by richaferry** [comment]
Oh i think i catch your issue steve. Still happening in pro version. but not happen in free version. fixing
