### ISSUE TITLE
PostTermsSave::fltTermsInput is breaking ACF taxonomy fields for non-hierarchical taxonomies (e.g. post_tag)

### ISSUE THREAD

**Issue by graham73may** [publishpress/PublishPress-Permissions#1285]
## Background
I have an ACF field to customise the UI of the core `post_tag` taxonomy.

There is an ACF taxonomy, field is set to: 
- For the `post_tag`
- Load terms enabled
- Save terms enabled

## Expected Behavior

When adding or editing content, if I select multiple terms (`one`, `two` and `three`) it should save with terms `one`, `two`, and `three`.

The expected behaviour is for it to save the multiple terms separately, for example a hierarchical taxonomy is treated correctly: 
 
![image](https://github.com/user-attachments/assets/64112c32-1222-4610-9c54-62127fad36c7)

## Current Behavior

When adding or editing content, if I select multiple terms (`one`, `two` and `three`) it currently saves as *one* combined term `one, two,three`.

Examples of the end result can be seen here: 
 
![image](https://github.com/user-attachments/assets/3e19b993-34ea-4ca9-8c52-8c82047c8737)

and here: 
 
![image](https://github.com/user-attachments/assets/420976ef-b0ed-4f90-9c23-e03bf75cf7f6)

## Possible Solution

I've xdebugged the issue as far as I can but can't resolve the issue without amending PublishPress Permissions ACF compatibility file. 

There appears to be a bug in `\PublishPress\Permissions\Compat\ACF::fltTaxonomyTerm` when it calls `\PublishPress\Permissions\Collab\PostTermsSave::fltTermsInput`

The array of term ids is send to `fltTermsInput`, but comes back as a string `1,2,3`

The problem only occurs for non-hierarchical taxonomies because of the `is_taxonomy_hierarchical()` check here: 

https://github.com/publishpress/PublishPress-Permissions/blob/master/modules/presspermit-collaboration/classes/Permissions/Collab/PostTermsSave.php#L217

This is the specific line causing the array to be converted to a string: 
https://github.com/publishpress/PublishPress-Permissions/blob/master/modules/presspermit-collaboration/classes/Permissions/Collab/PostTermsSave.php#L268

---

My current plan/workaround is to convert the post_tag taxonomy to become a hierarchical taxonomy and skip all of this. 

I don't know why the PostTermsSave is imploding the values or if this has been caused by changes on ACF's side, but it's currently non functional for non-hierarchical taxonomies. 

## Steps to Reproduce (for bugs)

1. Have ACF pro and PublishPress Permissions enabled
2. Import [acf-export-2024-12-13.json](https://github.com/user-attachments/files/18125328/acf-export-2024-12-13.json) (it should add the field to the `post` post type).
3. Add/Edit a post, select multiple tags and hit save / publish

## Context
This has made it impossible to save content with Tags.

## Your Environment
Version used:
- ACF Pro - Version 6.3.11
- Permissions - Version 4.0.34

**Comment by graham73may** [comment]
Workaround: 

```
/**
 * Convert the post_tag taxonomy to a hierarchical taxonomy.
 *
 * @ref: https://css-tricks.com/how-and-why-to-convert-wordpress-tags-from-flat-to-hierarchical/#aa-add-a-new-taxonomy-to-wordpress
 *
 * @return void
 */
function make_tags_hierarchical() {

	// Maintain the built-in rewrite functionality of WordPress tags

	global $wp_rewrite;

	$rewrite = array(
		'hierarchical' => false, // Maintains tag permalink structure
		'slug'         => get_option( 'tag_base' ) ? get_option( 'tag_base' ) : 'tag',
		'with_front'   => ! get_option( 'tag_base' ) || $wp_rewrite->using_index_permalinks(),
		'ep_mask'      => EP_TAGS,
	);

	// Redefine tag labels (or leave them the same)

	$labels = array(
		'name'                       => _x( 'Tags', 'Taxonomy General Name', 'hierarchical_tags' ),
		'singular_name'              => _x( 'Tag', 'Taxonomy Singular Name', 'hierarchical_tags' ),
		'menu_name'                  => __( 'Tags', 'hierarchical_tags' ),
		'all_items'                  => __( 'All Tags', 'hierarchical_tags' ),
		'parent_item'                => __( 'Parent Tag', 'hierarchical_tags' ),
		'parent_item_colon'          => __( 'Parent Tag:', 'hierarchical_tags' ),
		'new_item_name'              => __( 'New Tag Name', 'hierarchical_tags' ),
		'add_new_item'               => __( 'Add New Tag', 'hierarchical_tags' ),
		'edit_item'                  => __( 'Edit Tag', 'hierarchical_tags' ),
		'update_item'                => __( 'Update Tag', 'hierarchical_tags' ),
		'view_item'                  => __( 'View Tag', 'hierarchical_tags' ),
		'separate_items_with_commas' => __( 'Separate tags with commas', 'hierarchical_tags' ),
		'add_or_remove_items'        => __( 'Add or remove tags', 'hierarchical_tags' ),
		'choose_from_most_used'      => __( 'Choose from the most used', 'hierarchical_tags' ),
		'popular_items'              => __( 'Popular Tags', 'hierarchical_tags' ),
		'search_items'               => __( 'Search Tags', 'hierarchical_tags' ),
		'not_found'                  => __( 'Not Found', 'hierarchical_tags' ),
	);

	// Override structure of built-in WordPress tags
	register_taxonomy( 'post_tag',
		array(
			'post',
		),
		array(
			'hierarchical'      => true, // Was false, now set to true
			'query_var'         => 'tag',
			'labels'            => $labels,
			'rewrite'           => $rewrite,
			'public'            => true,
			'show_ui'           => true,
			'show_admin_column' => true,
			'_builtin'          => true,
		) );
}

add_action( 'init', 'make_tags_hierarchical' );
```

Outcome: 

![image](https://github.com/user-attachments/assets/74d490a7-ad35-47c1-84ca-1da3c5680abc)

**Comment by rizaardiyanto1412** [comment]
Thanks for reporting this. 

@agapetry Any idea on this one?
