### ISSUE TITLE
Conflict with PublishPress Authors after activating the "Enable Custom permissions for Authors"

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Permissions#150]
After activating the "Enable custom permissions for Authors" option in the author edit page the Authors list is broken and a duplicated footer appears in the authors edit page.

Removing the option "presspermit_enabled_taxonomies" fixes the issue.

![Screen Recording 2020-08-14 at 17 42 51-2](https://user-images.githubusercontent.com/407131/90291405-3cfd2c00-de56-11ea-93c5-c07d4ec3eb22.gif)

**Comment by agapetry** [comment]
@andergmartins All set to resolve this in the next release:  https://github.com/publishpress/PublishPress-Permissions/pull/152/commits/ce84b868d7022cd9ae61096dd3ccf83a8e14af01

**Comment by andergmartins** [comment]
Cool, Thanks @agapetry
