### ISSUE TITLE
Pro: Caption cleanup, correction in "File Access" area

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#206]
> For Nginx integration, see readme.txt in your plugins/file-access folder.
![Screen Shot 2020-09-25 at 3 27 02 PM](https://user-images.githubusercontent.com/3868028/94307960-bef76f00-ff43-11ea-9fa4-167bab93eec2.png)

**Comment by stevejburge** [comment]
Also on this screen, this text is unclear:

> If Media Library performance and disclosure would be acceptable.

Does that mean that is may produce a slowdown?

**Comment by stevejburge** [comment]
Can we just remove this whole screen?

<img width="1017" alt="remove-attachments-utility" src="https://user-images.githubusercontent.com/3868028/94309473-24e4f600-ff46-11ea-87d0-c1ff76426ed0.png">

This link could be a button instead:

![attachments-utility](https://user-images.githubusercontent.com/3868028/94309499-2e6e5e00-ff46-11ea-9903-f10070cb01e7.png)

**Comment by stevejburge** [comment]
OK, this screen requires a lot of work. Maybe we should make a "Media" menu link and include these settings too:
<img width="1348" alt="Screen Shot 2021-02-05 at 4 42 23 PM" src="https://user-images.githubusercontent.com/3868028/107092260-42b64780-67d1-11eb-921a-825c68e807e9.png">

**Comment by stevejburge** [comment]
Maybe include this also? 
"Enforce distinct edit, delete capability requirements for Media"
<img width="1258" alt="Screen Shot 2021-02-05 at 4 54 31 PM" src="https://user-images.githubusercontent.com/3868028/107093219-dfc5b000-67d2-11eb-8681-cfdc05b17c32.png">

**Comment by agapetry** [comment]
Here's a philosophical question to ponder.  Don't take this as an argument, just a discussion to be sure we don't replace one problem with another.  Several recent issue submissions seem to be driving at migrating the Permissions menu 

**from:** Users-like menu - Submenu items correspond to items which are edited as an expandable set of objects. Typically one Settings submenu item, if any.

**to:** a Settings-like menu - Seldom accessed, submenu items are meaningful groupings of settings.

Is that a conscious decision? I just want to be sure that we're thinking it through. What is the guiding principle to determine whether a group of settings is linked directly from the admin menu or as a Settings page tab?  I agree that Role Usage would have been better handled elsewhere, and worry a little about whether moving other setting tabs to the main plugin menu introduces new inconsistency or menu clutter.

My expectation for "Permissions > Media" would be a screen that lets me search or browse media and set permissions - not general settings for how Media permissions are applied.

**Comment by stevejburge** [comment]
@agapetry Fair points, yes - I think you're right here

**Comment by agapetry** [comment]
https://github.com/publishpress/PublishPress-Permissions-Pro/pull/313

**Comment by agapetry** [comment]
@stevejburge  There is some important clarification / disclaimer on this screen that would be lost if we dropped this screen completely. I've clarified these captions, though:

![image](https://user-images.githubusercontent.com/43488774/191783255-153304a6-929b-42e9-8a61-e2cfe001560f.png)

**Comment by stevejburge** [comment]
Thanks @agapetry 

The first sentence remains confusing (to me at least). The rest is clear.

I think we should probably schedule a specific release to update the Permissions settings to match the PublishPress standards

**Comment by agapetry** [comment]
@stevejburge "For post restrictions to be extended to files and images, those attachments must be formally defined (not just linked in the post content).  This utility scans post content to apply any missing attachments."

Is that clear?

**Comment by stevejburge** [comment]
@agapetry Thanks. Almost ... this part isn't quite clear: "those attachments must be formally defined (not just linked in the post content)"

**Comment by agapetry** [comment]
"For post restrictions to be extended to files and images, those attachments must be stored as post metadata (not just linked in the post content). This utility scans post content to apply any missing attachments."

I don't know how to simplify it any more without losing meaning.

**Comment by stevejburge** [comment]
@agapetry That's it! Thanks. Much clearer
