### ISSUE TITLE
Undefined index db_version on first activation

### ISSUE THREAD

**Issue by yanmorinokamca** [publishpress/PublishPress-Permissions#223]
With WP_DEBUG=true, press-permit-core generate two warnings of undefined index during first activation.
First file (the db_ver is already set but not used)
press-permit-core/classes/PublishPress/Permissions.php
```
- new Permissions\DB\DatabaseSetup($ver['db_version']);
+ new Permissions\DB\DatabaseSetup($db_ver);
```
https://github.com/publishpress/PublishPress-Permissions/blob/master/classes/PublishPress/Permissions.php#L212

Second file:
press-permit-core/modules/presspermit-import/classes/Permissions/ImportHooksAdmin.php
https://github.com/publishpress/PublishPress-Permissions/blob/master/modules/presspermit-import/classes/Permissions/ImportHooksAdmin.php#L72
```
- new Import\DB\DatabaseSetup($ver['db_version']);
+ $db_ver = ( isset( $ver['db_version'] ) ) ? $ver['db_version'] : ''; 
+ new Import\DB\DatabaseSetup($db_ver);
```
These corrections seems to pass the activation step.

**Comment by stevejburge** [comment]
Thanks for reporting this @yanmorinokamca
