### ISSUE TITLE
Getting Started screen for new installs

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#3]
There's a lot of work to do here, but one good first step would be to move the "Install" and "Import" tabs to the end, as the final tabs

<img width="617" alt="Screen Shot 2019-06-20 at 1 36 05 PM" src="https://user-images.githubusercontent.com/3868028/59869065-6d376080-9360-11e9-96ad-47dfe23a52ca.png">

> This is confusing. Where to start? Nothing very relevant to me above the Modules area. What are modules? If I deactivate them, will WordPress be faster? I take it these are features I can select. Lots of text to read, nothing visual. How do I decide what I need to build the workflow and content visibility rules I need? 
> 
> A “Getting Started” walkthrough or preloadable common defaults would be helpful here.

**Comment by agapetry** [comment]
related: https://github.com/publishpress/PublishPress-Permissions/issues/58
