### ISSUE TITLE
Error warning in Archives widget

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#307]
array_diff(): Expected parameter 1 to be an array, string given in /Users/steve/Local Sites/free-plugins/app/public/wp-content/plugins/press-permit-core/classes/PublishPress/Permissions/PostFilters.php on line 699

<img width="416" alt="Screen Shot 2021-01-15 at 1 04 48 PM" src="https://user-images.githubusercontent.com/3868028/104762405-4a368380-5732-11eb-8de9-bcc4b75e3fa1.png">

**Comment by agapetry** [comment]
https://github.com/publishpress/PublishPress-Permissions/pull/312
