### ISSUE TITLE
Sometimes the "Bulk Actions" dropdown just disappears

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#326]
![Screen Shot 2021-02-26 at 11 26 25 AM](https://user-images.githubusercontent.com/3868028/109326784-98589f80-7825-11eb-860a-f213475020b9.png)

**Comment by agapetry** [comment]
@stevejburge The Bulk action dropdown is not displayed if there are no deletable groups listed.

**Comment by stevejburge** [comment]
@agapetry It does appear at first. But if I click "Custom Group" and then come back again, it's gone.

But, maybe this issue will make it irrelevant https://github.com/publishpress/PublishPress-Permissions/issues/328
