### ISSUE TITLE
Pro: Enable Teaser module by default

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#354]
If Permissions is restricting content, we should make it easier to control that experience.

Can we set it so that:

1) the Teaser feature is a menu link in Pro
2) the feature is set to the WordPress default out-of-the-box (users need to change things to change the experience)
3) the design is easier to use

**Comment by stevejburge** [comment]
If we move this screen to it's own menu link, we can clean it up and make it much easier to use. Maybe a tabbed design like the new "Capabilities" screen?




<img width="1028" alt="Screen Shot 2021-08-30 at 1 43 45 PM" src="https://user-images.githubusercontent.com/3868028/131381856-93ef0577-c104-4d29-93aa-99c64ead5740.png">
<img width="1029" alt="Screen Shot 2021-08-30 at 1 43 59 PM" src="https://user-images.githubusercontent.com/3868028/131381865-95ee726b-8743-4ef5-8546-cd4de6bfaefd.png">

**Comment by htmgarcia** [comment]
@stevejburge you mean moving Teaser to its own Menu (without including the rest of tabs). Then in Teaser page convert "RSS Feeds", "Custom Fields" and "Hidden Content Teaser" in vertical tabs, correct?

**Comment by stevejburge** [comment]
@htmgarcia Yes, please. Exactly that

**Comment by htmgarcia** [comment]
@agapetry we need to move Teaser to its own menu (without displaying the other tabs), and do design improvements. If I try to move Teaser to its own page, I see high risk to break something in the process. May you help me a bit by moving Teaser content to its own page, so then I can focus on the design, please?

**Comment by agapetry** [comment]
@htmgarcia Okay, I can work on that after clearing some Revisions and Capabilities releases.

**Comment by htmgarcia** [comment]
@agapetry what is the status on this?

> May you help me a bit by moving Teaser content to its own page, so then I can focus on the design, please?

**Comment by agapetry** [comment]
@htmgarcia This branch is not fully functional, but should allow you to start working on the Teaser UI changes: https://github.com/publishpress/PublishPress-Permissions-Pro/tree/teaser-move-to-separate-page

**Comment by agapetry** [comment]
https://github.com/publishpress/PublishPress-Permissions-Pro/tree/teaser-new-settings-ui
