### ISSUE TITLE
Rename permission groups?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#4]
From a customer

> “Anonymous” and “Authenticated” are ambiguous, technical terms. “Logged in” and  “Not logged in” are more accessible.
> 
> What is the significance of the different brackets?

<img width="624" alt="Screen Shot 2019-06-20 at 1 37 50 PM" src="https://user-images.githubusercontent.com/3868028/59869155-a8399400-9360-11e9-83ad-81422f6cf7a6.png">

**Comment by agapetry** [comment]
Yes, answered this in another ticket :)

**Comment by agapetry** [comment]
The requested metagroup name changes were applied in the previously linked PR.
