### ISSUE TITLE
Pro: BuddyPress Groups not linked on Permission Groups screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#403]
BuddyPress groups no longer appear in the "Groups" screen.

Even after clicking "Permissions" and saving a group, they don't appear:
<img width="374" alt="Screen Shot 2021-04-27 at 4 20 21 PM" src="https://user-images.githubusercontent.com/3868028/116307666-9ef78a80-a774-11eb-9da1-8ef21658a850.png">

**Comment by agapetry** [comment]
FYI, this change applies to Permissions > Groups, not the BuddyPress Groups screen.
