### ISSUE TITLE
UI for the Permissions group in User accounts

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#44]
If you edit a user account profile, there is a PublishPress settings area.

This is really hard to read:

![permission-groups-1](https://user-images.githubusercontent.com/3868028/66427389-d14e6500-e9e1-11e9-961f-da06f04bc6f3.png)

**Comment by agapetry** [comment]
Yep, I can clean that up.

**Comment by agapetry** [comment]
We eliminated the group name truncation later that year without isolating the change to a PR:

![image](https://user-images.githubusercontent.com/43488774/191605294-afc65434-1e18-48c9-a8f8-819dd76c5730.png)
