### ISSUE TITLE
Plugin appears to wipe out {taxonomy}_children option fields

### ISSUE THREAD

**Issue by vena** [publishpress/PublishPress-Permissions#456]
Seeing a strange issue here. Steps to reproduce on a fresh Wordpress 5.8 install:

* Create a category in the admin UI
* Create a child category of the previous category
* Check category_children in wp_options, it will be a serialized array.
* Install/activate PublishPress Permissions, current v3.5.7
* Check category_children, it may already be empty
* Create another child category in the admin UI
* Check category_children, it's definitely now empty

The category_children option never gets refilled so long as PP Permissions is active. Deactivating PP Permissions and deleting or adding a category will refill the option.

This option is used for caching parent/child relationships, emptying it causes many term-related template tags to malfunction.

**Comment by agapetry** [comment]
@vena The {$taxonomy}_children entries are intentionally cleared because their presence as a term cache prevents the necessary filters from being applied.

**Comment by vena** [comment]
unfortunately, leaving it empty appears to cause queries for term children to silently fail and return an empty array rather than falling back to the database to rebuild.

**Comment by vena** [comment]
In case you folks can find a way this side-effect can be avoided, here's an example of a common pattern for an archive template that returns an empty array when the {taxonomy}_children cache is missing:
```php
$this_term     = \get_queried_object();
$term_children = \get_terms( [ 'taxonomy' => $this_term->taxonomy, 'parent' => $this_term->term_id, 'hide_empty' => false ] );
```

**Comment by emidiao** [comment]
I'm having the same problem described in this issue, with the latest plugin version 3.8.4
category_children in wp_options keeps getting deleted whenever I make a change to a category or a permission, and it reappears if I uninstall the plugin and update a category
