### ISSUE TITLE
Improve horizontal tabs for Settings page

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Permissions#468]
Use this design:
![horizontal-tabs](https://user-images.githubusercontent.com/4999794/139347302-e43720d3-3728-468b-87ed-c713d4e5f3bc.png)

**Comment by htmgarcia** [comment]
@agapetry is safe if I work on this task? If so, which branch should I use?

**Comment by agapetry** [comment]
@htmgarcia You can use or clone this branch to work on the settings tab if desired:

https://github.com/publishpress/PublishPress-Permissions-Pro/tree/teaser-new-settings-ui
