### ISSUE TITLE
Content is not displayed when loading Teaser tab 

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Permissions#472]
@agapetry this section is displayed only when unchecking and checking back Enable teaser:
![Screen Shot 2021-11-05 at 13 56 39](https://user-images.githubusercontent.com/4999794/140571066-e3b63da7-e78c-46eb-b716-fab7db5a4d94.png)

Related to https://github.com/publishpress/PublishPress-Permissions-Pro/pull/222

**Comment by agapetry** [comment]
https://github.com/publishpress/PublishPress-Permissions-Pro/pull/310

**Comment by agapetry** [comment]
https://github.com/publishpress/PublishPress-Permissions/issues/354
