### ISSUE TITLE
Allow flexibility to output checkboxes 

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Permissions#473]
May we adjust these fields to allow to split in two columns as with the rest of fields, please? Currently output the HTML through `optionCheckbox()` method 
![Screen Shot 2021-11-05 at 13 59 52](https://user-images.githubusercontent.com/4999794/140571349-171d9c72-8a01-4a5d-89a4-3717318d81ef.png)
![Screen Shot 2021-11-05 at 13 59 45](https://user-images.githubusercontent.com/4999794/140571352-f233e377-debf-405a-8e9c-d3ba34d33547.png)

Related to https://github.com/publishpress/PublishPress-Permissions-Pro/pull/222

**Comment by agapetry** [comment]
@htmgarcia Since you already seem to be hiding those lower post type checkboxes on a "no teaser" dropdown selection, there will also need to be some logic to hide the section labels "Tease on Direct Access" etc. when all the checkboxes are hidden.  Otherwise their presence is confusing.

**Comment by agapetry** [comment]
https://github.com/publishpress/PublishPress-Permissions/issues/354
