### ISSUE TITLE
Tidy up box that appears on each user account screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#480]
@htmgarcia Can we tidy up this box that appears on each user account screen when Permissions is installed?

<img width="769" alt="Screen Shot 2021-11-10 at 12 03 20 PM" src="https://user-images.githubusercontent.com/3868028/141159422-ca7fc771-2ea6-4dd3-99d9-e5d43862d96b.png">

**Comment by htmgarcia** [comment]
@stevejburge how can I reach this content?

**Comment by stevejburge** [comment]
@htmgarcia If you have Permissions installed, and any custom group, this will appear at the bottom of any user account

**Comment by htmgarcia** [comment]
@stevejburge starter proposal:
![Screen Shot 2021-11-12 at 8 52 11](https://user-images.githubusercontent.com/4999794/141486280-a08ea50c-bc3a-48d1-97c4-bfed16d4c532.png)

**Comment by stevejburge** [comment]
That works great, thanks @htmgarcia
