### ISSUE TITLE
Disable message on install

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#483]
We don't need this:
<img width="986" alt="Screen Shot 2021-11-12 at 3 33 31 PM" src="https://user-images.githubusercontent.com/3868028/141531045-d7200139-d9f7-4ee4-993a-1a7c6753c1f2.png">
:

**Comment by agapetry** [comment]
@stevejburge We're also talking about disabling more Permissions modules by default. That would seem to require more guidance at initial plugin activation, not less.  Do we need to talk about designing a Getting Started screen or guided configuration steps?

**Comment by stevejburge** [comment]
I think a Getting Started guide would help. We do also need to clean up the Settings screen https://github.com/publishpress/PublishPress-Permissions/issues/3

**Comment by agapetry** [comment]
https://github.com/publishpress/PublishPress-Permissions/issues/3
