### ISSUE TITLE
Installation message is confusing

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#50]
<img width="629" alt="Screen Shot 2019-11-27 at 11 36 40 AM" src="https://user-images.githubusercontent.com/3868028/69742118-36812580-110a-11ea-98a4-ef6c8cb36085.png">

> This is a somewhat unusual looking post-install notice, which lacks the usual top and bottom margins as seen in the green activation notice. 
> 
> Red = Bad! Warning! Error! Not “Thanks!”
> 
> The appearance of a link worries me: must I immediately define settings for the plugin to work at all? Why is this setting so important? Will this notice disappear leave me wondering how to find the right settings? 
> 
> Maybe this is not the best way to start. Soft onboarding without urgency might be better.

**Comment by htmgarcia** [comment]
@agapetry what are the required steps to reach the "Thanks for activating" message from the screenshot above? Tried by enabling the Pro plugin with no luck.

**Comment by agapetry** [comment]
@htmgarcia I already changed that notice. It now looks like this: 
![image](https://user-images.githubusercontent.com/43488774/79920420-18d89380-83fe-11ea-9502-fce0d79c55d0.png)

If you want to display it, the easiest way is to hit the "Revert to Defaults" button on Permissions > Settings.  Then de/re-activate.  Of course, you won't want to do that later if you have specific settings configured for testing.  In that case, use phpMyAdmin to delete the wp_options rows with option_name = 'presspermit_enabled_post_types' and option_name 'presspermit_enabled_taxonomies'

**Comment by agapetry** [comment]
We need some kind of message like this so people understand there is a required configuration step.  Auto-enabling post type filtering is not good either because the Admin needs some awareness and responsibility for modifications to their data access.

**Comment by htmgarcia** [comment]
Thanks for the clarification @agapetry !

**Comment by stevejburge** [comment]
I'm reopening this. Maybe we don't remove it, but instead we improve the message.

Maybe our plugins have a standard welcome message?

**Comment by htmgarcia** [comment]
@stevejburge Sorry. I'm out of ideas here. @agapetry what do you think?

**Comment by stevejburge** [comment]
@htmgarcia I'm going to close this. We'll create a standard welcome message for our plugins
