### ISSUE TITLE
Odd characters in Preferences Panel

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Permissions#506]
![Screen Shot 2021-11-25 at 15 16 48](https://user-images.githubusercontent.com/4999794/143500569-de5e19ad-4232-4496-bec2-8af2de1cfd98.png)

**Comment by htmgarcia** [comment]
@stevejburge are you able to reproduce this issue? While editing a post, go to Preferences > Panel
![Screen Shot 2021-12-20 at 19 02 56](https://user-images.githubusercontent.com/4999794/146853344-dc199f75-9a8d-4745-8c21-7bf984902af9.png)

**Comment by stevejburge** [comment]
@htmgarcia Sorry, nothing obviously wrong here

**Comment by htmgarcia** [comment]
@stevejburge my mistake. I made the test in the wrong way.
