### ISSUE TITLE
Remove horizontal banner

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#508]
We're retiring this in favor of the sidebar banner
<img width="696" alt="Screen Shot 2021-11-26 at 8 17 36 AM" src="https://user-images.githubusercontent.com/3868028/143587005-46564bcd-9a92-4c0a-8ddd-79b15e2014da.png">

**Comment by htmgarcia** [comment]
@stevejburge this one belongs to Capabilities. Is already covered in https://github.com/publishpress/PublishPress-Capabilities/pull/250
