### ISSUE TITLE
Remove the [ ] {  } from user roles

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#53]
I'm not sure these extra tags are helpful. A couple of users have asked why they are there:

<img width="307" alt="Screen Shot 2019-08-09 at 9 42 09 AM" src="https://user-images.githubusercontent.com/3868028/62783247-01cd5d80-ba8a-11e9-9213-5bac31c8f12d.png">

**Comment by stevejburge** [comment]
From a user:

> Unclear: What is the significance of the square versus curly brackets? Frontend vs. backend focused permission rule groups?

**Comment by agapetry** [comment]
The brackets are to indicate the group is not created or populated by PublishPress Permissions, but defined as a WordPress role.  Maybe there's a cleaner way to indicate that, but I think removing the brackets without any distinction would cause confusion in the other direction (why can't I delete this group or change its members?)

Agreed on eliminating the square / curly distinction.

**Comment by stevejburge** [comment]
@agapetry Would a column on this page work? The column would show either "User Role" or "Custom Group"
