### ISSUE TITLE
Teaser should have it's own admin link

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#54]
As with Sync Posts, this really isn't a settings. It's a powerful feature that deserves it's own admin menu link:

<img width="801" alt="Screen Shot 2019-08-09 at 9 37 44 AM" src="https://user-images.githubusercontent.com/3868028/62783010-7653cc80-ba89-11e9-822c-220e7ef0fa22.png">

**Comment by agapetry** [comment]
I think what we really need here is a templating system. Then the parts that are actually settings can remain on the tab with a cleaner presentation.

**Comment by stevejburge** [comment]
@agapetry Thanks. Can you expand on that more? Maybe @htmgarcia can help

**Comment by agapetry** [comment]
https://github.com/publishpress/PublishPress-Permissions-Pro/commit/54096ca9b0901a8f4ed5fe18792806efbfa38806
