### ISSUE TITLE
Sync Posts should have it's own menu link

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#55]
This isn't a settings. It's a powerful feature that should stand alone with it's own admin menu link:
<img width="1323" alt="Screen Shot 2019-08-09 at 9 36 36 AM" src="https://user-images.githubusercontent.com/3868028/62782931-41477a00-ba89-11e9-9a59-e639565025a4.png">

**Comment by agapetry** [comment]
Yeah, I agree on making that an improvement task.

**Comment by agapetry** [comment]
There is something to clarify here, though.  The Sync Posts functionality is not just an on-demand operation.  This tab also determines actions that are performed automatically at new user creation. So in that sense, it is a setting.

**Comment by stevejburge** [comment]
@agapetry I hear you, but this is such a big and important feature, it really deserves to be shown some in its own menu link. It will get a lot more people using it

**Comment by agapetry** [comment]
https://github.com/publishpress/PublishPress-Permissions-Pro/commit/54096ca9b0901a8f4ed5fe18792806efbfa38806
