### ISSUE TITLE
Pro: Member, Premium, Staff etc are not explained

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#56]
> What are "Member," "Premium," and "Staff?"
> 
> My first reaction was to ask "Did that come from this plugin?"
> 
> These are not in the defined permission groups I can see at Permissions > Groups, so how did they get here?
> 
> How would I change them?

<img width="434" alt="Screen Shot 2019-11-27 at 11 44 59 AM" src="https://user-images.githubusercontent.com/3868028/69742876-7a285f00-110b-11ea-8e7a-0306048fe6f1.png">

**Comment by agapetry** [comment]
Those are privacy statuses (or should I say "Post Visibilities") that are defined by default.

Can you elaborate on why these would be expected to show up in Permissions > Groups?

**Comment by stevejburge** [comment]
Sorry, this was a quote from a customer. I think we're just doing a poor job of explaining these. features currently.

Maybe in this screenshot they could be labelled. "Privacy Statuses" could be a label like "Title", "Slug", or "Date".
