### ISSUE TITLE
"Logged in" and "Not logged in" are better than "Anonymous" and "Authenticated" 

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#57]
> "Anonymous" and "Authenticated" are ambiguous, technical terms. "Logged in" and "Not logged in" are more accessible and possibly more precise.
<img width="569" alt="Screen Shot 2019-11-27 at 11 46 51 AM" src="https://user-images.githubusercontent.com/3868028/69742958-9d530e80-110b-11ea-9fde-04d82b49a5b8.png">

**Comment by agapetry** [comment]
I can agree with that! Changing...
