### ISSUE TITLE
Move or hide Install options for extra modules

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#58]
> Why install? It's already installed. This is confusing. Where to start? Nothing very relevant to me above the Modules area. What are modules? If I deactivate them, will WordPress be faster? I take it these are features I can select. Lots of text to read, nothing visual. How do I decide what I need to build the workflow and content visibility rules I need?
> 
> A "Getting Started" walkthrough or preloadable common defaults would be helpful here.
<img width="570" alt="Screen Shot 2019-11-27 at 11 47 48 AM" src="https://user-images.githubusercontent.com/3868028/69743036-beb3fa80-110b-11ea-84cd-a0f91f7f5fa8.png">

**Comment by agapetry** [comment]
From my perspective, all modules except Collaborative Publishing are niche functionality that will not be needed on the majority of installations.  That being the case, module opt-in:  
- Enhances site performance by not loading unnecessary code
- Simplifies administrative UI by omitting irrelevant tabs and menu items
- Reduces our support burden from users tripping over functionality they would not have chosen

I do agree that a friendlier "Getting Started" section would be helpful here.

**Comment by stevejburge** [comment]
Thanks. Maybe we split this into tabs?

- License Key
- Enable features (with improved descriptions of what exactly each feature does)
