### ISSUE TITLE
Pro: Status tab is confusing

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#60]
> I can't easily make sense of this. I can only click the two text links, which go to screens under the Permissions > Post Statuses menu item, but I can't reach them any other way. I see how I can create a new Privacy Status, but it seems I need PublishPress active to add a new Workflow Status.
> 
> Naming is hard! The division of "Statuses" into Privacy and Workflow categories take a minute to comprehend. My sense is that this way of organizing them under the "Status" heading is confusing and simply following the WP architecture, which end users may not understand, and it is probably not a helpful heuristic here. I want to define backend user workflows and frontend privacy or visibility rules.

<img width="572" alt="Screen Shot 2019-11-27 at 11 50 20 AM" src="https://user-images.githubusercontent.com/3868028/69743233-1bafb080-110c-11ea-9a82-0c350bd750d6.png">

**Comment by agapetry** [comment]
>>> I can't easily make sense of this. I can only click the two text links, which go to screens under the Permissions > Post Statuses menu item, but I can't reach them any other way.

Those links are a shortcut to **Permissions > Statuses > Visibility**  and **Permissions > Statuses > Workflow**

Maybe part of the confusion is that Permissions > Statuses > Visibility should be recaptioned to "Privacy"

**Comment by agapetry** [comment]
>>>  I see how I can create a new Privacy Status, but it seems I need PublishPress active to add a new Workflow Status.

Does that need to be stated more directly? Without PublishPress, you cannot create custom Workflow statuses, but the default workflow statuses still have some meaningful configuration.

**Comment by agapetry** [comment]
>>> The division of "Statuses" into Privacy and Workflow categories take a minute to comprehend. My sense is that this way of organizing them under the "Status" heading is confusing and simply following the WP architecture, which end users may not understand, and it is probably not a helpful heuristic here. I want to define backend user workflows and frontend privacy or visibility rules.

If we want to decouple those conceptually, I think "status" should continue to be associated with publication workflow.  We could more easily move privacy statuses out from under the "status" umbrella completely and just refer to them as Post Visibilities.

For workflow, I think the word "status" is already out of the bag.

**Comment by stevejburge** [comment]
@agapetry This is a customer quote, but I think is key point is that the naming is confusing.

Yes, we need consistent naming: either "Privacy" or "Visibility". Plus could "Workflow" be better?

Maybe these?

- Privacy/Visibility = Viewing Statuses
- Workflow = Editing Statuses

**Comment by agapetry** [comment]
Resolved by PublishPress Statuses release and integrations.
