### ISSUE TITLE
(all) Exception Not Visible in GUI Display

### ISSUE THREAD

**Issue by TEKgeist** [publishpress/PublishPress-Permissions#634]
When I added the 1st exception rule for (all), it added successfully.  No errors were indicated.  But, this exception rule has never shown up on the screen.  I thought it was an issue with WAF, security, or another plugin.  I ended disabling all plugins, all security, and it didn't change.  Then, when I added the next 2 rules, I noticed they showed up just fine.  Then, I realized this had nothing to do with security at all.

Here is an image of the GUI display showing 2 of the 3 rules.
[Missing (all) Rule](https://i.ibb.co/W3ypw1F/Screenshot-2022-04-28-090249.png)

Here is an image of the WP_PPC_EXCEPTIONS table to show the 3 rules.
[Data in WP_PPC_EXCEPTIONS table](https://i.ibb.co/tYJsbKr/Screenshot-2022-04-28-090143.png)

Let me know what could be causing this.

**Comment by stevejburge** [comment]
Hi @TEKgeist 

Thanks for using PublishPress. Sorry, Github is for bug reports. I'd recommend another support option for this:

https://publishpress.com/publishpress-support/
"This option is for genuine bugs that can be reproduced on other sites. This is not for support questions about your site. For questions about your site, please choose another option on this page."

**Comment by TEKgeist** [comment]
I'm sorry.  I just assumed it was a bug.  So, you are able to (all) exceptions on your install?  I will reach out them to with the same info.

**Comment by stevejburge** [comment]
Thanks @TEKgeist. Can you reproduce this on a clean test site?

**Comment by TEKgeist** [comment]
I'm sorry.  I have not been able to even attempt this.  I just know that after removing all plugins from Wordpress and all WAF security completely, it was still only showing 2 of the 3 exceptions as noted in my pictures.  It's a standard updated Wordpress install with no other plugins present.  I'm going to post this to the Support forum.  Would you be able to help me there?

**Comment by stevejburge** [comment]
Sure, the support guidance is here: https://publishpress.com/publishpress-support/

"If you are not a PublishPress member, please post in the WordPress.org “Support” area. We aim to answer all these questions, but can not offer guarantees."

**Comment by agapetry** [comment]
@TEKgeist I found that new Category permissions for "(all)" post types have not been saved correctly since version 3.7.  This is corrected in the linked pull request, which will be included in next week's release.

**Comment by TEKgeist** [comment]
Thanks for fixing this guys.  I really appreciate your quick action and efforts!
