### ISSUE TITLE
Read capability added to logged-out users by default

### ISSUE THREAD

**Issue by mathieuhays** [publishpress/PublishPress-Permissions#649]
Hi,

I've set the `show_admin_bar` filter on my website as follows:
```php
add_filter('show_admin_bar', function() {
	return current_user_can('read');
});
```

The expected behaviour is that the admin bar is only shown to users with the `read` capability. Logged-out users don't have that capability.

What's actually happening is that the `current_user_can('read')`  function returns `true` for logged-out users. ~This only started happening in WordPress 6.0.0. It seems to only be happening in the `show_admin_bar` filter.~ If I run that function in `functions.php` directly the function is correctly returning `false`.

I've tested this on a fresh install with a default theme and no other plugins running and can confirm the issue only happens when the Permissions plugin is activated.

WordPress Version: 6.0.0
Plugin Version: 3.7.5
PHP Version: 7.4.29

Thanks

**Comment by agapetry** [comment]
@mathieuhays A quick fix is to call is_user_logged_in() instead.

**Comment by mathieuhays** [comment]
Thanks for the suggestion @agapetry. In my use-case I do have a category of users without the `read` capability as they only have access to a member area on the front-end.

I did use the following as a workaround in the meantime:
```php
return is_user_logged_in() && current_user_can( 'read' );
```

**Comment by agapetry** [comment]
@mathieuhays This is probably due to your filter not being added prior to WP 6.0.  In previous versions, the filter application occurs prior to functions.php execution.

**Comment by mathieuhays** [comment]
My bad. I did some further testing. Turns out it was already happening prior to WordPress 6.0.0, I just never tested my website while logged-out between installing this plugin and upgrading to WordPress 6.0.0. Sorry for that.

I've found the origin of the issue. The `read`capability gets added in the function linked below:
https://github.com/publishpress/PublishPress-Permissions/blob/ddd970f9ec0db85f57e2d89a493391c1f70a4156/classes/PublishPress/Permissions/Roles.php#L21

FYI the `read` capability is used to grant admin access as defined in the WordPress documentation:
https://wordpress.org/support/article/roles-and-capabilities/#read

I would recommend changing this default behaviour as it could potentially create security issues for plugin/theme authors that rely on said capability for any type of admin-related functionality. This kind of rule should be opt-in only, not a default.

**Comment by agapetry** [comment]
@mathieuhays Under the current permissions model, if anonymous users did not have that capability added, they would not be able to read published posts. I'm looking into addressing this, but it's not as simple as just changing that line you noted.

**Comment by agapetry** [comment]
@mathieuhays Can you confirm that the attached PR resolves the issue for you? We expect to include it in a release early next week.

**Comment by mathieuhays** [comment]
@agapetry It does! Thanks for sorting this out

**Comment by agapetry** [comment]
@mathieuhays Since this solution caused issues for some other sites, I had to revert it.  With the current Permissions release (3.7.8), you will need to add the following constant definition to wp-config.php (or another module that executes prior to plugin init):

`define('PRESSPERMIT_READ_PUBLIC_CAP', 'read_public');`
