### ISSUE TITLE
Posts screen: Invalid post counts with "Hide non-editable posts"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#65]
If you have "Hide non-editable posts" enabled, the numbers still show for post filters:

<img width="386" alt="Screen Shot 2020-01-07 at 11 39 09 AM" src="https://user-images.githubusercontent.com/3868028/71911796-6298b900-3142-11ea-880a-3e8f0d463f05.png">

**Comment by agapetry** [comment]
@stevejburge This looks like it was either fixed or dependent on a certain configuration or plugin interaction.
