### ISSUE TITLE
Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Permissions#68]
Found this error in a client's site:

>Uncaught TypeError: $ is not a function
source:https://www.da-pulse.com/wp-content/plugins/presspermit-pro/modules/presspermit-status-control/common/lib/custom-privacy-block.min.js?ver=2.9
line:79

**Comment by andergmartins** [comment]
Another error on the same site:

>TypeError: $ is not a function
    at PPCustomPostStatusInfo (custom-status-block.min.js?ver=2.9:148)


jQuery is only loaded as "jQuery" and not $. This can probably be fixed adding the code to closures like:

`jQuery(function($) {
...
});`

or 

`(function($) {
...
})(jQuery)`

**Comment by agapetry** [comment]
This issue was resolved in 0389eeb and released in version 3.0
