### ISSUE TITLE
Publish press throws errors when using functions from the plugin specifically on the customize admin screen

### ISSUE THREAD

**Issue by thesquaremedia** [publishpress/PublishPress-Permissions#686]
Fatal error: Uncaught Error: Call to undefined function CShop\Crate\pp_get_groups() in /code/wp-content/themes/crate/inc/filters.php:121 Stack trace: #0 /code/wp-includes/class-wp-hook.php(307): CShop\Crate\add_custom_group_caps('') #1 /code/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #2 /code/wp-includes/plugin.php(476): WP_Hook->do_action(Array) #3 /code/wp-admin/admin.php(175): do_action('admin_init') #4 /code/wp-admin/customize.php(13): require_once('/code/wp-admin/...') #5 {main} thrown in /code/wp-content/themes/crate/inc/filters.php on line 121

`/**
 * Modify custom permission group user capabilities
 */
function add_custom_group_caps() {
	
	// Allow anyone assigned to a custom group the cap to upload files
	$groups = pp_get_groups(
		'pp_group',
		array(
			'cols'            => 'id',
			'skip_meta_types' => array( 'wp_role' ),
		)
	);
	foreach ( $groups as $group ) {
		$custom_group_users = pp_get_group_members( $group->id, 'pp_group', 'id' );
		foreach ( $custom_group_users as $user_id ) {
			$user = new \WP_User( $user_id );
			$user->add_cap( 'upload_files' );
			$user->add_cap( 'list_others_unattached_files' );
			$user->add_cap( 'pp_list_all_files' );
		}
	}
}
add_action( 'admin_init', __NAMESPACE__ . '\add_custom_group_caps' );`

this error only triggers on the /wp-admin/customize.php everywhere else in the frontend/admin its fine. something is causing the plugin to not load correctly in the customizer. see also https://wordpress.org/support/topic/undefined-pp_get_groups-error/#post-15733527 for more details on already performed debugging and tried solutions.

**Comment by stevejburge** [comment]
Thanks @thesquaremedia 

We've debugged this with you and Kevin replied: "The stack trace shows this is related to your custom code."

We will look at this if we have time, but the only way to get guaranteed support for custom code is with a Pro membership at PublishPress.
