### ISSUE TITLE
Getting blank page when creating new page

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Permissions#688]
ISSUE: If a group has read permission for a limited page, will get blanks when creating new

STEP TO REPLICATE: 

1. Edit roles
2. Set it to read limited page (check picture)
![image](https://user-images.githubusercontent.com/83811723/176883956-ec667d82-59bd-4c09-a1f7-21e1cd6edb66.png)

3. Log in to that custom role
4. Create a new page
5. Observe the issue, it will show you a blank page instead

**Comment by agapetry** [comment]
@rizaardiyanto1412 The Permission assignment you show there is actually a restriction preventing the role from reading any page other than "Project A."  The Gutenberg Editor checks reading permissions on page edit.  Although that overlap between editing and reading permissions is technically a bug in reference to expected Permissions functionality, in practice this is not a realistic configuration that we need to support.  A user won't be creating new pages that they are unable to read.

**Comment by rizaardiyanto1412** [comment]
@agapetry Ah I see. That totally makes sense. Thanks for checking
