### ISSUE TITLE
Query Loop block: Sticky posts displayed redundantly

### ISSUE THREAD

**Issue by spliner21** [publishpress/PublishPress-Permissions#713]
On my front page layout (FSE) I use Query Loop block to display a section of most important entries in which I query for **pinned** posts only. I have five such posts on my page, but I check that it doesn't really matter.

When I am logged in as admin everything works fine, posts are displayed one time. 
But when I try to display the page without logging in or if I am logged in as different (non-admin) user, this section display all entries twice (posts 1, 2, 3, 4, 5  and then again posts 1, 2, 3, 4, 5).

Today I've discovered one more thing - in Query Loop block you can limit number of results per page. So if I set the limit to "4", then first repetition goes without limit (1, 2, 3, 4, 5) and then second repetition goes limited (1, 2, 3, 4).

Once I tried to eliminate the problem source I found out that it is caused by this very plugin which I otherwise like very much so I don’t want to search for a replacement if not necessary.
Please help me with resolving this issue.

My WordPress installation is up-to-date (latest WordPress, all plugins updated). Issue happens in all browsers and on all devices.

If you need any more details please let me know.

**Comment by rizaardiyanto1412** [comment]
Confirmed

Step to replicate:
1. Pin some of your posts (4 posts)
2. Create new page
3. Add Query loop block
4. Choose data source: post
5. And choose include Sticky post
6. Save and publish
7. View on incognito
8. Observe issue, the loop is double
