### ISSUE TITLE
Posts screen: Don't hide non-editable posts by default

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#74]
It should be possible to check or uncheck the "Hide non-editable posts" box

**Comment by agapetry** [comment]
There is more to this issue; I'll make a note to explain next week.

**Comment by stevejburge** [comment]
One more reason to do this: https://wordpress.org/support/topic/posts-are-not-displayed-in-the-dashboard/

**Comment by agapetry** [comment]
@stevejburge That setting was deprecated in favor of implementing "list" capabilities:

- list_published_posts
- list_others_posts
- list_published_pages
- list_others_pages

etc.

So resolving this issue will involve expanding the Capabilities UI to expose these capabilities.  It needs to be done in a way that indicates they are an alternative for partial access, not required when the role has the equivalent "edit" capability.  Once that UI is in place, we can link to it from Permissions > Settings.

**Comment by stevejburge** [comment]
Thanks @agapetry 

One of the things I'd like to improve with Permissions (particularly Pro) is not making an active changes when it's first installed.

Could we make this feature opt-in in Permissions?
