### ISSUE TITLE
Pro: Permissions Pro language files are not applied

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#775]
@wocmultimedia has a question: 

> Presspermit-pro/Permissions Pro has two file .pot (presspermit-pro.pot and presspermit-pro-hints.pot) shall I have to translate both or which one?

**Comment by wocmultimedia** [comment]
Hi there,

I think the language .pot is not in sync yet in Permissions Pro.
Can someone explain me why I don't find the strings shown in the shot below and as well as I cannot visualize my translation even though I removed the free version of Permissions and made several tests? Is there maybe something wrong in the filename? Besides inside the folder languages are two file.pot and neither of them contains the strings afore mentioned.
Let me understand if I'm wrong in doing something. 
![shot-Permit-Pro1](https://user-images.githubusercontent.com/2352240/200324441-c769bd34-97c5-498a-a062-3a017384b13a.jpg)
![shot-Permit-Pro2](https://user-images.githubusercontent.com/2352240/200324486-7c3861d1-4208-485a-9665-6207e629d28d.jpg)
![shot-Permit-Pro3](https://user-images.githubusercontent.com/2352240/200324975-d6addaca-6043-41e7-9c4e-f3690a16f45c.jpg)
Thanks,
Angelo
