### ISSUE TITLE
Add a PHP filter for {Authenticated} Permission Group membership

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#79]
This is from @alpinejosh

 One thing that would be really awesome is  if there was a filter for {Authenticated} which authorizes users from a PHP filter.

```
add_filter(
‘presspermit_authenticated_users’,
function($authenticated) {
// user IDs to allow users to edit, view, or revise post
$authenticated = 1,2,3;
})
```

This would allow us to show post’s to our BuddyPress, Peepso, Ultimate Member friends by having something like $authenticated = $social_friends_ids. Privacy aside it would enable our friends to be contributors to posts we make. By having a filter to have $authenticated control which users can do an action we could then write out our own conditions to determine if the variable is used. The filter mentioned could only apply where {Authenticated} option is selected for better fine tuning.

**Comment by JoshLewy** [comment]
Another variable that would be helpful is $not_authenticated which removes them from being included within {Authenticated}. This way if there are users who are listed under $authenticated but should be removed can be excluded.
