### ISSUE TITLE
Improve the Permissions box design

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#80]
The main box area is not bad, but could use some small cleaning-up:
![Screen Shot 2020-04-20 at 1 16 41 PM](https://user-images.githubusercontent.com/3868028/79780019-4859a400-8309-11ea-850f-47127bfa4d87.png)

For example, the tabs are very small. Plus, they are styled like links rather than tabs

![Screen Shot 2020-04-20 at 1 17 51 PM](https://user-images.githubusercontent.com/3868028/79780102-6a532680-8309-11ea-9d2e-57f0c967a8a6.png)

Compare to Yoast, for example:

![Screen Shot 2020-04-20 at 1 18 34 PM](https://user-images.githubusercontent.com/3868028/79780137-76d77f00-8309-11ea-931e-9bcb2a8ded73.png)

Also, I don't think these links are useful:
![Screen Shot 2020-04-20 at 1 19 47 PM](https://user-images.githubusercontent.com/3868028/79780260-a1293c80-8309-11ea-885f-b4b3cf2c88e8.png)

**Comment by htmgarcia** [comment]
@stevejburge current progress:
<img width="931" alt="Screen Shot 2020-04-20 at 20 05 31" src="https://user-images.githubusercontent.com/4999794/79813829-54158c80-8342-11ea-938d-0afdd8b0eebc.png">

**Comment by stevejburge** [comment]
@htmgarcia That's right direction, thanks

**Comment by agapetry** [comment]
Regarding the role / group name links, would there be any harm in leaving the link but removing the link-decoration (underlining)? On some sites, there is a configuration review convenience in jumping from the "Permissions for this this post" screen to the "Permissions for this group" screen.  If the link is hidden, it can still function for users who know what they're looking for, without misleading those who don't.

**Comment by stevejburge** [comment]
@agapetry Yes, sure thing. That works

**Comment by htmgarcia** [comment]
@agapetry @stevejburge text-decoration removed 
<img width="341" alt="Screen Shot 2020-05-14 at 13 00 14" src="https://user-images.githubusercontent.com/4999794/81969097-06a7da80-95e3-11ea-9bc0-447cccdeb1e0.png">
