### ISSUE TITLE
Improve the Users tab

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#83]
This request is identical to https://github.com/publishpress/PublishPress-Permissions/issues/81

Can we bring this tab into 2020?
![users](https://user-images.githubusercontent.com/3868028/79781415-6fb17080-830b-11ea-9c4b-dd6ee85bfc6e.png)

**Comment by htmgarcia** [comment]
@stevejburge the changes from #81 apply automatically to this one:
<img width="546" alt="Screen Shot 2020-04-23 at 18 00 15" src="https://user-images.githubusercontent.com/4999794/80157657-4d7a5580-858c-11ea-81fd-59ad37edd9a3.png">

**Comment by stevejburge** [comment]
Thanks @htmgarcia I think this is a good first improvement.

Perhaps later we can improve the Javascript here (move to chosen select box, for example)

**Comment by htmgarcia** [comment]
@stevejburge may you elaborate the chosen select box suggestion?

**Comment by stevejburge** [comment]
@htmgarcia https://harvesthq.github.io/chosen/

**Comment by htmgarcia** [comment]
@stevejburge got it :) #89
