### ISSUE TITLE
List Others capabilities do not work restrictively

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Permissions#849]
I have Permissions Pro installed which should automatically hide others users post based on this post: https://publishpress.com/blog/hide-peoples-posts-wordpress-admin/#:~:text=You%20can%20do%20it%20by,now%20only%20see%20their%20posts

![image](https://user-images.githubusercontent.com/83811723/225325145-38d3ac44-d515-4d74-bd0f-bb6db1f94ef4.png)

![image](https://user-images.githubusercontent.com/83811723/225325204-81e80990-4258-4612-a1be-5c40db8a0da0.png)

![image](https://user-images.githubusercontent.com/83811723/225325273-ee37d6ca-567c-48b3-b7a3-14b9f851cd21.png)

**Comment by agapetry** [comment]
@rizaardiyanto1412 Although the Capabilities UI implies that "list" capabilities should work as all others, in fact they are only designed and implemented within PublishPress Permissions as supplemental permissive capabilities.  I'm not sure if it's feasible to make them work restrictively.

**Comment by agapetry** [comment]
I suggest treating this as a UI issue for now, meaning @olatechpro should stop the negation from being offered for the List capabilities.

**Comment by rizaardiyanto1412** [comment]
@agapetry That left me with my original goal question. How can I hide other's users' post?

**Comment by agapetry** [comment]
@rizaardiyanto1412 The normal solution is to remove the role's ability to **edit** other user's posts. That also prevents them from being listed.

**Comment by rizaardiyanto1412** [comment]
@agapetry Remove edit_other capability only remove the edit capability, it is still being listed 
![image](https://user-images.githubusercontent.com/83811723/234523076-7fac37fc-8986-4d72-867d-f2c33fffb209.png)

**Comment by stevejburge** [comment]
@rizaardiyanto1412 I've opened a couple of issues on the Capabilities repo.

Please follow up if this remains an issue
