### ISSUE TITLE
Not working: Enabling viewing permissions to private posts by Categories

### ISSUE THREAD

**Issue by ingridskard** [publishpress/PublishPress-Permissions#874]
I need to be able to let Groups give Users access to _private_ posts associated with specific categories. 

GUI gives the impression this is possible:
![image](https://user-images.githubusercontent.com/54002074/231504618-66cb258d-cee7-41ee-aba4-c011a7768960.png)

However when I give that group to users they still can't see private posts in that category.

It's not clear to me whether this could be part of paid features, please advise:
![image](https://user-images.githubusercontent.com/54002074/231506879-1b3673e2-4c1c-4b60-8d9d-ca4c98e7575f.png)

Smells like a bug, or what do you think?

TYSM.

**Comment by stevejburge** [comment]
@ingridskard Sorry, Github is for confirmed bugs not for general questions: https://publishpress.com/publishpress-support/
