### ISSUE TITLE
Move to a chosen select box

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Permissions#89]
https://harvesthq.github.io/chosen/
<img width="546" alt="Screen Shot 2020-04-23 at 18 00 15" src="https://user-images.githubusercontent.com/4999794/80157657-4d7a5580-858c-11ea-81fd-59ad37edd9a3.png">

**Comment by htmgarcia** [comment]
@stevejburge I like the idea, however technically all the users and custom groups from a site would be outputted on the <select> at once, even if all remains invisible until are selected. May work for custom groups however currently the functionality for Custom groups and Users is the same.

**Comment by stevejburge** [comment]
Thanks @htmgarcia. Maybe a good first step is making the search box much larger and easier to use?

Is there any way for the search box to work automatically, without clicking "Search"?

**Comment by htmgarcia** [comment]
@stevejburge we can get rid of the search button and use that space to make the search box larger, however functionality would be the same. In this step I wouldn't recommend doing changes to functionality, instead only focus on design improvements and consistency.

btw, I edited my previous comment because the tag < select > was hidden. In case that part didn't make sense.

**Comment by stevejburge** [comment]
@htmgarcia OK, that works. Small steps for now

**Comment by agapetry** [comment]
@stevejburge Do you mean you want it to have "live search" functionality that auto-refreshes the results as you type?

**Comment by stevejburge** [comment]
@agapetry Yep, that's the idea
