### ISSUE TITLE
Incongruence between the file pot inside the languages folder

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Permissions#909]
Hi @andergmartins @htmgarcia @stevejburge ,
I have found an incongruence between the file pot inside the languages folder and the translation files inside the same folder as well as the main WP folder in my local machine. I just updated the plugin to latest release.
Please, let me know if with latest release did you change the string quantity of the file pot.
Because the new file pot has 582 strings, the press-permit-core-it_IT.po 763 strings that I updated yesterday with previous file pot and the press-permit-core-it_IT.po in the main WP content> languages>plugins folder has 733 strings.
Can you tell me, what do I have to do? Which one is correct, the file pot or what?

Besides online in the WP system, the string quantity is 783 with 771 translated. I'm updating this one and waiting for your reply about file .pot in the plugin folder
Thanks
Angelo

**Comment by agapetry** [comment]
@wocmultimedia I've just checked in the .pot file as regenerated by poEdit from the current source. As you can see, it has 590 entries.

Note that there is also a press-permit-core-hints pot file with source strings bearing a corresponding text domain. These are the "advanced notes" captions displayed when you click on the "comments" icon on the Settings screen. Strings from the Role Scoper Import module (which should probably be dropped soon) are also spearated out this way. I split them up so these strings can be treated as a lower translation priority.  As such, the .pot file is configured to omit those strings from the main press-permit-core.pot

In addition, strings in classes/PublishPress/Permissions/Constants.php are excluded from press-permit-core.pot for the same reason.

Please let me know if you find this arrangement problematic.

**Comment by agapetry** [comment]
@wocmultimedia Steve is back.

**Comment by wocmultimedia** [comment]
Hi @agapetry , @stevejburge ,
I checked and fixed some strings in press-permit-core-it_IT and also translated the Hints strings for the three languages ES-FR-IT.
Here's the files  please, add to language folder and eventually overwrite old one if present.
Thanks,
Angelo
[FREE_Press-permit-core-hints_translations ES-FR-IT-August2023.zip](https://github.com/publishpress/PublishPress-Permissions/files/12474988/FREE_Press-permit-core-hints_translations.ES-FR-IT-August2023.zip)
