### ISSUE TITLE
Improve the "Edit Permission Group" screen for user roles

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#91]
Go to Permissions > Groups and edit a user role (Authors, Editors etc)

<img width="521" alt="Screen Shot 2020-04-29 at 10 12 27 AM" src="https://user-images.githubusercontent.com/3868028/80606149-f1875500-8a01-11ea-9959-b6dee8f788a8.png">
<img width="852" alt="Screen Shot 2020-04-29 at 10 13 12 AM" src="https://user-images.githubusercontent.com/3868028/80606214-0cf26000-8a02-11ea-8d11-e19cb8a0b99b.png">

Could we tighten up the design of these pages, using some of the improvements from https://github.com/publishpress/PublishPress-Permissions/issues/80

**Comment by stevejburge** [comment]
This gets worse in the Pro version. If you enable the Pro features:
<img width="535" alt="Screen Shot 2020-04-29 at 10 21 25 AM" src="https://user-images.githubusercontent.com/3868028/80607505-948c9e80-8a03-11ea-9d54-b366290a43b5.png">

... we also get this messy box:
<img width="598" alt="Screen Shot 2020-04-29 at 10 21 44 AM" src="https://user-images.githubusercontent.com/3868028/80607552-a5d5ab00-8a03-11ea-93d5-ebe14289d815.png">

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Permissions/commit/5a91c73ecb3ec3ab2a750fb888ff74cf0d28c22a

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Permissions/commit/768c939b3e68915848bff61c98fe8e7def2231f1 
https://github.com/publishpress/PublishPress-Permissions/commit/c4f1ab87beed47d1599d5fe5d4ed207381f6dbda

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Permissions/commit/43a497f9be85d895df0a09583eda915a652f735d

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Permissions/commit/79187d213adcd2cb740efc5c8be95838348fb068
https://github.com/publishpress/PublishPress-Permissions/commit/16f3388772e87426a80c452c8d81620d67caa0f5

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Permissions/commit/a015577b5611d5338f473009409190b06c22f181

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Permissions/commit/ac41a36fbdcd05c1168904fd32e379a0a6c91f35
https://github.com/publishpress/PublishPress-Permissions/commit/90a4eefaeee33a532166e43f631315b31d468d74
https://github.com/publishpress/PublishPress-Permissions/commit/792a8c04bd49e49f232a5e829ce07382b201be9f

**Comment by htmgarcia** [comment]
@stevejburge unfortunately the improvements for the Pro version can't be added now due I would need to reproduce manually all the changes from the Free repository due the code seems independent on each repository. I think @agapetry is working on some improvements to avoid having duplicated code.

**Comment by htmgarcia** [comment]
Some screenshots of current progress (free version only)
<img width="451" alt="Screen Shot 2020-05-11 at 17 13 57" src="https://user-images.githubusercontent.com/4999794/81617339-dfff5f00-93aa-11ea-82b6-536b3dd27a22.png">
<img width="769" alt="Screen Shot 2020-05-11 at 17 13 42" src="https://user-images.githubusercontent.com/4999794/81617340-e1308c00-93aa-11ea-8833-dce3e8603ee7.png">
<img width="494" alt="Screen Shot 2020-05-11 at 17 13 18" src="https://user-images.githubusercontent.com/4999794/81617344-e261b900-93aa-11ea-9729-37807dfa1da0.png">

**Comment by stevejburge** [comment]
@htmgarcia Definitely an improvement. Thanks!

**Comment by agapetry** [comment]
The styling looks good!

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Permissions-Pro/commit/050c1d4c51f0940ddbc10161238d81b2ca2f0128

**Comment by htmgarcia** [comment]
> This gets worse in the Pro version. If you enable the Pro features:
> <img alt="Screen Shot 2020-04-29 at 10 21 25 AM" width="535" src="https://user-images.githubusercontent.com/3868028/80607505-948c9e80-8a03-11ea-9d54-b366290a43b5.png">
> 
> ... we also get this messy box:
> <img alt="Screen Shot 2020-04-29 at 10 21 44 AM" width="598" src="https://user-images.githubusercontent.com/3868028/80607552-a5d5ab00-8a03-11ea-93d5-ebe14289d815.png">

@stevejburge may I have the exact steps to reach these screens, please?

**Comment by stevejburge** [comment]
@htmgarcia 
- Use Permissions Pro
- Make sure all the Pro features are enabled, including "Access Circles"
- Create a new Permission group
