### ISSUE TITLE
Improve the "Edit Permission Group" screen for groups

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#93]
This is very similar to https://github.com/publishpress/PublishPress-Permissions/issues/91 but slightly different

- Go to Permissions > Groups 
- Click "Custom Group"
- Click "Add new"
- Edit your new group

Particularly with the Pro features enabled, this screen is messy:

<img width="1124" alt="Screen Shot 2020-04-29 at 10 33 13 AM" src="https://user-images.githubusercontent.com/3868028/80608535-e71a8a80-8a04-11ea-90c1-8da679909fe4.png">

**Comment by htmgarcia** [comment]
@stevejburge the free version doesn't seem to have support for new custom groups. I get "Sorry, you are not allowed to access this page." message after. Please correct me if I'm wrong?

**Comment by htmgarcia** [comment]
cc @agapetry

**Comment by stevejburge** [comment]
@htmgarcia Sorry, that is the Pro version. We use the Free repo for both Free and Pro issues

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Permissions-Pro/commit/ee17528a0e842e5e386aee5a598334a7099ad9a8
