### ISSUE TITLE
String is not registered on free version translation

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Permissions#994]
I translated the plugin to Bahasa Indonesia. It's already 100%: https://translate.wordpress.org/locale/id/default/wp-plugins/press-permit-core/

However there are some text that are still remain in English. 
For example:
![image](https://github.com/publishpress/PublishPress-Permissions/assets/83811723/d92b74c0-e94a-4c0f-8a9a-b27badcd733f)
![image](https://github.com/publishpress/PublishPress-Permissions/assets/83811723/dbff27fb-00ad-4d3e-b71e-60ac5b5ed6cb)

Steve found out same thing happen on Spanish as well:
![image](https://github.com/publishpress/PublishPress-Permissions/assets/83811723/85492ad2-3ac5-4d73-b0c1-b0ede03a4302)

**Comment by stevejburge** [comment]
@agapetry Do we just want to hide all these Pro options from the Free version? 

At the very least, we can move the "Modules" tab to the last tab
